import MainLayout from "@/components/Layout/MainLayout";
import React, { ReactElement } from "react";
import style from "@/styles/index.module.scss";
import Modal from "@/components/ui/modal";
import CommodityForm from "@/components/Forms/CommodityForm";
import Head from "next/head";

const AddCommodity = () => {
  return (
    <>
      <Head>
        <title>Add Commodity | eFishery</title>
        <meta name="efishery" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal backDropClose />
      <main className={style.main_container}>
        <CommodityForm crud="add" />
      </main>
    </>
  );
};

export default AddCommodity;

AddCommodity.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};
